# Generated by Django 4.1.3 on 2022-11-16 16:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=34, validators=[django.core.validators.MinLengthValidator(34)], verbose_name='address')),
                ('time_unit', models.CharField(choices=[('D', 'day(s)'), ('H', 'hour(s)')], default='H', max_length=1, verbose_name='time unit')),
                ('initial_time', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='initial time')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 11, 16, 16, 53, 59, 468729, tzinfo=datetime.timezone.utc), verbose_name='start time')),
            ],
        ),
    ]
