# Generated by Django 4.1.3 on 2022-11-16 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersupply',
            name='minute_price',
            field=models.IntegerField(default=1, verbose_name='price per minute'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 21, 21, 35, 82011, tzinfo=datetime.timezone.utc), verbose_name='start time'),
        ),
    ]
