# Generated by Django 4.1.3 on 2022-11-17 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_powersupply_last_device_amount_powersupply_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 13, 54, 10, 842381, tzinfo=datetime.timezone.utc), verbose_name='start time'),
        ),
    ]
