# Generated by Django 4.1.3 on 2022-11-17 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_powersupply_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersupply',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 13, 55, 21, 961653, tzinfo=datetime.timezone.utc), verbose_name='start time'),
        ),
    ]
